# Generated by Django 4.0.2 on 2022-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('passwordMd5', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('joiningDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
