# Generated by Django 4.0.2 on 2022-02-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_passwordmd5_user_password_sha256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joiningDate',
            new_name='joining_date',
        ),
    ]
