# Generated by Django 4.0.2 on 2022-02-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
