# Generated by Django 4.0.2 on 2022-02-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_participation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
