# Generated by Django 4.0.2 on 2022-02-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='totalScore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
