# Generated by Django 4.0.2 on 2022-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(default={'ff': 'ff'}),
            preserve_default=False,
        ),
    ]
