# Generated by Django 4.0.2 on 2022-02-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
    ]
