# Generated by Django 4.0.2 on 2022-02-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_alter_participation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
