# Generated by Django 4.0.2 on 2022-02-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_rename_totalscore_quiz_total_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['quiz'], name='Quiz_partic_quiz_id_85aa2f_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user'], name='Quiz_partic_user_id_b0824c_idx'),
        ),
    ]
