# Generated by Django 4.0.2 on 2022-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_participation_quiz_partic_quiz_id_85aa2f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['start_time'], name='Quiz_quiz_start_t_42f1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['end_time'], name='Quiz_quiz_end_tim_7c4405_idx'),
        ),
    ]
